### ISSUE TITLE
stopping the camera, and editing the settings

### ISSUE THREAD

**Issue by tanipolansky** [arnefmeyer/RPiCameraPlugin#4]
Hi Arne, thank you so much for this software. I'm setting it up with my rasberry pi to use in the lab i work for. 
i downloaded everything and got into the proper directory pi@raspberrypi:~/RPiCameraPlugin/Python/scripts $ 

and have two problems
1- the code to start it - python rpi_host.Py standalone works, but when it starts it fills the screen and theres no code or button to close/stop the recording

2- i tried the code with --h to get the options up. for some reason i think this is shooting at 30 or 60 fps and i need to up the frame rate, as well as flip it over. im not sure how to integrate the --vflip command or framerate option in a way that will affect what is shown on screen when i start the camera
thank you So much !!!

**Comment by arnefmeyer** [comment]
Hi, Issue 1 is probably related to the fullscreen preview window that is shown above all other windows:
https://picamera.readthedocs.io/en/release-1.13/api_camera.html#picamera.PiCamera.start_preview

Note that there are no buttons etc in the standalone mode. You can use the optional --timeout argument to set the duration of the recording (and ctrl+c to stop it earlier if needed). I haven't tested this but it is also possible to set the size of the preview window, e.g.,
camera.start_preview(fullscreen=False, window = (100, 20, 640, 480))

I just updated the code so it should be possible to pass the arguments via the "controller.start_preview(...)" call in the "run_standalone" function (in rpi_host.py)

Issue 2: did you try "python rpi_host.py standalone --framerate 90 --vflip"?
