### ISSUE TITLE
h.264 files seem to have no container

### ISSUE THREAD

**Issue by nimrodlbr** [arnefmeyer/RPiCameraPlugin#7]
Hello Arne, thank you for developing this plugin! 

I am using the plugin to record eye tracking videos through the run_standalone() command. 

The video output has the title "video_name.h264" but it seems to be in no particular container codec (not recognized as an h.264 file on the RPi, linux and windows systems) and when force played by VLC runs at 29.97 FPS instead of the 60 FPS which it was recorded in via the plugin. 

I couldn't figure out why the files are not contained, it seems like you specified a format through picamera.PiVideoEncoder (VideoEncoderGPIO in the code), but the output file is problematic for some reason. 

I've tried using ffmpeg to re-contain it in an mp4 file with the correct frame-rate but I can't be certain that ffmpeg doesn't duplicate / drops frames while converting so I have been trying to understand how to change your code to send the output as a contained file - is there something I'm missing? How did you intend the files to be saved on the RPi (format-wise)? how did you read these files? 

Thank you in advance, and sorry for being a beginner :) 

Nimrod Leberstein

**Comment by arnefmeyer** [comment]
Hey Nimrod, 

You can wrap the h264 file into an MP4 container using MP4Box. It's part of the gpac package (`sudo apt install -y gpac`).

In your case this should work `MP4Box -fps 60 -add video_name.h264 video_name.mp4`.

I will add a note to the README file as someone else might have the same issue.

Arne

**Comment by nimrodlbr** [comment]
Thank you for the quick reply! 

This seems to work well - I'm not sure what happens to the time-stamps going through the mp4box, I'll look into what it does specifically understand if something is duplicated or moved in the process. 

Thanks again, wonderful plugin! 

Nimrod
