### ISSUE TITLE
Integrating with windows based open-ephys version v0.5.3.1

### ISSUE THREAD

**Issue by nimrodlbr** [arnefmeyer/RPiCameraPlugin#8]
Hello again, and thank you for the previous reply! 

This may be my own misunderstanding and not an actual issue but I couldn't make the plugin work with the windows plugin architecture - The newer Open-Ephys GUI versions offer a plugin installer and I'm trying to figure out the correct way to build the plugin around it. 

Is the plugin compatible with this windows version? Is there something I'm missing? or is it simply a matter of using a correct build procedure?

Again, much appreciation for the work and responsiveness!

Nimrod

**Comment by arnefmeyer** [comment]
I haven't used the plugin installer (and I am also not using the GUI under Windows) but I guess the installer is currently only supporting "official" OE plugins. Have you tried to build the plugin from source?

**Comment by nimrodlbr** [comment]
I have, and it works perfectly, but only on a Linux machine...

I'll try to build the gui from source on windows and let you know if I can make the plugin work with it

Thanks! :)

**Comment by nimrodlbr** [comment]
Okay, so in order to build the plugin from source I've built the gui and when running the cmake command while trying to build the plugin I get this output:

Input = 
"
cmake -G "Visual Studio 16 2019" -A x64 ..
"
Output = 
"
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
-- The C compiler identification is MSVC 19.24.28314.0
-- The CXX compiler identification is MSVC 19.24.28314.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
C:/Program Files/Open Ephys/RPiCameraPlugin-master/RPiCamera/ZMQ_INCLUDE_DIRS
   used as include directory in directory C:/Program Files/Open Ephys/RPiCameraPlugin-master/RPiCamera
ZMQ_LIBRARIES
    linked by target "RPiCamera" in directory C:/Program Files/Open Ephys/RPiCameraPlugin-master/RPiCamera
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
"

I understand that this is a problem with the ZeroMQ installation - should I change something in the CMakeLists? the zeromq libraries are unzipped as per the instructions given [here](https://zeromq.org/download/) - does this no-installation seem right to you? 

Thanks for the support here - much appreciated!

Nimrod

**Comment by arnefmeyer** [comment]
Do the zmq library files that you downloaded match those specified at the bottom in the CMakeLists.txt file? There are some hard-coded file names that might need to be changed:

```
find_library(ZMQ_LIBRARIES NAMES libzmq-v120-mt-4_0_4 zmq zmq-v120-mt-4_0_4)
find_path(ZMQ_INCLUDE_DIRS zmq.h)
```

**Comment by nimrodlbr** [comment]
Sorry for the lag replying - compiling these from source is proving difficult for me

The libraries I have are libzmq-v141-4_3_2 and I couldn't find the version which fits the CMakeLists.txt

should I change the CMakeLists.txt to fit the libzmq version I have or find the one specified? 
another question is where should the libzmq files be in relation to the RPiCamera directory when I try to compile?

**Comment by arnefmeyer** [comment]
yes, try changing the file names in the CMakeLists.txt file. 

The CMAKE_LIBRARY_PATH environment variable defines where to look for when CMake tries to find an installation of a required external library, i.e., when issuing a find_library() command in a CMakeLists.txt:
https://cmake.org/cmake/help/latest/variable/CMAKE_LIBRARY_PATH.html

I don't use Windows/VS but as cmake is cross-platform it might also work in your case.

**Comment by nimrodlbr** [comment]
I tried changing the names -while the build happens alright, the end result is a broken application, I'll try again and maybe read a little about the visual studio fundamentals I'm missing in order to build this properly and understand what each step is doing. 

The linux version is still working and I'll use the code in standalone mode via SSH with OE GUI recording TTL events until I can make the build work. 

Thanks again for all the help!
